ENCODING: utf-8

ROUTES:
  update_dashboard: /update-dashboard

# Сервер (DASHBOARD)
DASHBOARD:
  HOST: 0.0.0.0
  PORT: 5000
  SAVE_FILE: system_database.csv

# Клиент (AGENT)
AGENT:
  SERVER_URL: https://sec.weforks.org
  LOCAL_URL: http://localhost:5000
  CSV_FILE: AA_csv_to_server.csv

# GitHub Webhook для автообновления
WEBHOOK:
  ALLOWED_BRANCH: "refs/heads/master"
  REPO_PATH: "/repo"
